server:
  port: 9090


spring:
  datasource:
    dynamic:
      # 是否开启 SQL日志输出，生产环境建议关闭，有性能损耗
      p6spy: true
      druid:
        filters: stat,wall,config #配置在监控统计拦截的filters，去掉后监控界面SQL无法进行统计，wall用于防火墙
        max-active: 100 #最大连接数
        initial-size: 1 #初始化大小
        max-wait: 60000 #获取连接等到超时时间
        min-idle: 1 #最小连接数
        time-between-eviction-runs-millis: 60000 #间隔多久才进行一次检测，检测需要关闭的空闲连接，单位为毫秒
        min-evictable-idle-time-millis: 300000   #一个连接在池中最小生存的时间，单位是毫秒
        validation-query: select 'x'
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        pool-prepared-statements: true
        max-open-prepared-statements: 50
        max-pool-prepared-statement-per-connection-size: 20
        stat-view-servlet:
          enabled: true
      # 配置默认数据源
      primary: master
      datasource:
        # 数据源-1，名称为 master
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://39.105.171.192/earthsiterbac?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
          username: root
          password: 123456
          # 数据源-2，名称为 slave
        slave:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://39.105.171.192/earthsite?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
          username: root
          password: 123456
  messages:
    encoding: utf-8
  servlet:
    multipart:
      max-file-size: 102400MB
      file-size-threshold: 102400MB
      max-request-size: 102400MB

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  redis:
    # Redis数据库索引（默认为 0）
    database: 0
    content-database: 1
    # Redis服务器地址
    host: 39.105.171.192
    #   host: 127.0.0.1

    # Redis服务器连接端口
    port: 6379
    # Redis 密码
    password:
    jedis:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 0
  aop:
    proxy-target-class: true

  freemarker:
    cache: false
    settings:
      template_update_delay: 0

#mybatis plus 设置
mybatis-plus:
  type-aliases-package: edu.xpu.cs.lovexian.systemadmin.domain,edu.xpu.cs.lovexian.systemadmin.generator.entity,edu.xpu.cs.lovexian.app.api.entity,edu.xpu.cs.lovexian.app.appadmin.entity
  mapper-locations: classpath:mapper/*/*.xml
  configuration:
    jdbc-type-for-null: null
  global-config:
    # 关闭 mybatis-plus的 banner
    banner: false

management:
  endpoints:
    web:
      exposure:
        include: ['httptrace', 'metrics','health']

earthsite:
  time:
    # 每天2点执行
    cron: 0 0 2 * * *
  ftlpath: D:\\
  playmask-scale: 100
  # 是否异步记录用户操作日志
  openAopLog: true
  # 单次最大批量入库数量
  max:
    batch:
      insert:
        num: 1000

  shiro:
    # 后端免认证接口 url
    anonUrl: /system/login/login,/system/logout/**,/system/admin/check/**,/api/**,/fileupload/smallfile
    # token有效期，单位秒
    jwtTimeOut: 36000
  swaggerShow:
      show: true
